# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe15f5b9ebfa427e43be0434e4a9fcd49530554fc3332b814cda73c1eb9f57cad4e832559709565bf937cb6a4955c26cf99fa5ca3fc041b677e963b65a95dc4

test:
  secret_key_base: 1aa0d2429d209de916153530e66d9a7b3fe03265f3c23f4c3a960dcfeb52800770ba990086a1bb53565b133bf1919b94214b70b2425837e49f0fdcc1fc59aa62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
